{
  "hash": "a8e183981f02740a44eae61d80aac096",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"HW7.1\"\nauthor: 'Sanghoo Ahn'\ndate: '2024-09-09'\ncategories: [bigdata]\njupyter: python3\n---\n\n\n## 문제 1.\n\n**데이터를 로드하고, 로지스틱 회귀모델을 적합하고, 회귀 표를 작성하세요.**\n\n::: {#17bddc5c .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport statsmodels.api as sm\n\ndf = pd.read_csv('../../data/leukemia_remission.txt', sep='\\t')\ndf\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>REMISS</th>\n      <th>CELL</th>\n      <th>SMEAR</th>\n      <th>INFIL</th>\n      <th>LI</th>\n      <th>BLAST</th>\n      <th>TEMP</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>0.80</td>\n      <td>0.83</td>\n      <td>0.66</td>\n      <td>1.9</td>\n      <td>1.10</td>\n      <td>1.00</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>0.90</td>\n      <td>0.36</td>\n      <td>0.32</td>\n      <td>1.4</td>\n      <td>0.74</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0</td>\n      <td>0.80</td>\n      <td>0.88</td>\n      <td>0.70</td>\n      <td>0.8</td>\n      <td>0.18</td>\n      <td>0.98</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.87</td>\n      <td>0.87</td>\n      <td>0.7</td>\n      <td>1.05</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1</td>\n      <td>0.90</td>\n      <td>0.75</td>\n      <td>0.68</td>\n      <td>1.3</td>\n      <td>0.52</td>\n      <td>0.98</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.65</td>\n      <td>0.65</td>\n      <td>0.6</td>\n      <td>0.52</td>\n      <td>0.98</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1</td>\n      <td>0.95</td>\n      <td>0.97</td>\n      <td>0.92</td>\n      <td>1.0</td>\n      <td>1.23</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>0</td>\n      <td>0.95</td>\n      <td>0.87</td>\n      <td>0.83</td>\n      <td>1.9</td>\n      <td>1.35</td>\n      <td>1.02</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.45</td>\n      <td>0.45</td>\n      <td>0.8</td>\n      <td>0.32</td>\n      <td>1.00</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>0</td>\n      <td>0.95</td>\n      <td>0.36</td>\n      <td>0.34</td>\n      <td>0.5</td>\n      <td>0.00</td>\n      <td>1.04</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>0</td>\n      <td>0.85</td>\n      <td>0.39</td>\n      <td>0.33</td>\n      <td>0.7</td>\n      <td>0.28</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>0</td>\n      <td>0.70</td>\n      <td>0.76</td>\n      <td>0.53</td>\n      <td>1.2</td>\n      <td>0.15</td>\n      <td>0.98</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>0</td>\n      <td>0.80</td>\n      <td>0.46</td>\n      <td>0.37</td>\n      <td>0.4</td>\n      <td>0.38</td>\n      <td>1.01</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>0</td>\n      <td>0.20</td>\n      <td>0.39</td>\n      <td>0.08</td>\n      <td>0.8</td>\n      <td>0.11</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.90</td>\n      <td>0.90</td>\n      <td>1.1</td>\n      <td>1.04</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>1</td>\n      <td>1.00</td>\n      <td>0.84</td>\n      <td>0.84</td>\n      <td>1.9</td>\n      <td>2.06</td>\n      <td>1.02</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>0</td>\n      <td>0.65</td>\n      <td>0.42</td>\n      <td>0.27</td>\n      <td>0.5</td>\n      <td>0.11</td>\n      <td>1.01</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.75</td>\n      <td>0.75</td>\n      <td>1.0</td>\n      <td>1.32</td>\n      <td>1.00</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>0</td>\n      <td>0.50</td>\n      <td>0.44</td>\n      <td>0.22</td>\n      <td>0.6</td>\n      <td>0.11</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>1</td>\n      <td>1.00</td>\n      <td>0.63</td>\n      <td>0.63</td>\n      <td>1.1</td>\n      <td>1.07</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.33</td>\n      <td>0.33</td>\n      <td>0.4</td>\n      <td>0.18</td>\n      <td>1.01</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>0</td>\n      <td>0.90</td>\n      <td>0.93</td>\n      <td>0.84</td>\n      <td>0.6</td>\n      <td>1.59</td>\n      <td>1.02</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>1</td>\n      <td>1.00</td>\n      <td>0.58</td>\n      <td>0.58</td>\n      <td>1.0</td>\n      <td>0.53</td>\n      <td>1.00</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>0</td>\n      <td>0.95</td>\n      <td>0.32</td>\n      <td>0.30</td>\n      <td>1.6</td>\n      <td>0.89</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>1</td>\n      <td>1.00</td>\n      <td>0.60</td>\n      <td>0.60</td>\n      <td>1.7</td>\n      <td>0.96</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>1</td>\n      <td>1.00</td>\n      <td>0.69</td>\n      <td>0.69</td>\n      <td>0.9</td>\n      <td>0.40</td>\n      <td>0.99</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>0</td>\n      <td>1.00</td>\n      <td>0.73</td>\n      <td>0.73</td>\n      <td>0.7</td>\n      <td>0.40</td>\n      <td>0.99</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#e4898481 .cell execution_count=2}\n``` {.python .cell-code}\nmodel = sm.formula.logit(\"REMISS ~ CELL + SMEAR + INFIL + LI + BLAST + TEMP\", data=df).fit()\n\nprint(model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOptimization terminated successfully.\n         Current function value: 0.399886\n         Iterations 10\n                           Logit Regression Results                           \n==============================================================================\nDep. Variable:                 REMISS   No. Observations:                   27\nModel:                          Logit   Df Residuals:                       20\nMethod:                           MLE   Df Model:                            6\nDate:                Tue, 10 Sep 2024   Pseudo R-squ.:                  0.3718\nTime:                        09:47:01   Log-Likelihood:                -10.797\nconverged:                       True   LL-Null:                       -17.186\nCovariance Type:            nonrobust   LLR p-value:                   0.04670\n==============================================================================\n                 coef    std err          z      P>|z|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept     64.2581     74.965      0.857      0.391     -82.670     211.187\nCELL          30.8301     52.135      0.591      0.554     -71.353     133.013\nSMEAR         24.6863     61.526      0.401      0.688     -95.903     145.275\nINFIL        -24.9745     65.281     -0.383      0.702    -152.923     102.974\nLI             4.3605      2.658      1.641      0.101      -0.849       9.570\nBLAST         -0.0115      2.266     -0.005      0.996      -4.453       4.430\nTEMP        -100.1734     77.753     -1.288      0.198    -252.567      52.220\n==============================================================================\n\nPossibly complete quasi-separation: A fraction 0.11 of observations can be\nperfectly predicted. This might indicate that there is complete\nquasi-separation. In this case some parameters will not be identified.\n```\n:::\n:::\n\n\n## 문제 2.\n**해당 모델은 통계적으로 유의한가요? 그 이유를 검정통계량를 사용해서 설명하시오.**\n\n::: {#34d28e5e .cell execution_count=3}\n``` {.python .cell-code}\nfrom scipy.stats import chi2\np_val=1-chi2.cdf(-2*(-17.186 + 10.797), df=6)\np_val\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\nnp.float64(0.04669995098322843)\n```\n:::\n:::\n\n\n> p-value: 0.04669995098322843 이므로 유의수준 0.05보다 작다 --> 유의함\n\n\n## 문제 3.\n**유의수준이 0.2를 기준으로 통계적으로 유의한 변수는 몇개이며, 어느 변수 인가요?**\n\n::: {#c24a66a6 .cell execution_count=4}\n``` {.python .cell-code}\nfrom scipy.stats import norm\n(1-norm.cdf(30.8301/52.135))*2 # cell 0.5542850639621408\n(1-norm.cdf(24.6863/61.526))*2 # smear 0.6882481267876992\n(norm.cdf(-24.9745/65.281))*2 # infil 0.702039210194285\n(1-norm.cdf(4.3605/2.658))*2 # li 0.10089726232517515 < 0.2\n(norm.cdf(-0.0115/2.266))*2 # blast 0.9959507356304004 \n(norm.cdf(-100.1734/77.753))*2 # temp 0.19762271242612317 < 0.2\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nnp.float64(0.19762271242612317)\n```\n:::\n:::\n\n\n> 유의수준 0.2를 기준으로 통계적으로 유의한 변수는 2개, 유의한 변수는 LI(0.101), TEMP(0.198)이다.\n\n\n## 문제 4. \n**다음 환자에 대한 오즈는 얼마인가요?**\n\n::: {#a7d0c4b0 .cell execution_count=5}\n``` {.python .cell-code}\n# CELL : 65%\n# SMEAR : 45%\n# INFIL : 55%\n# LI : 1.2\n# BLAST : 1.1세포/μL\n# TEMP : 0.9\nlog_odds = 64.2581 + 30.8301 * 0.65 + 24.6863 * 0.45 - 24.9745 * 0.55 + 4.3605 * 1.2 - 0.0115 * 1.1 - 100.1734 * 0.9\nodds = np.exp(log_odds)\nodds # 0.03817459641135519\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\nnp.float64(0.03817459641135519)\n```\n:::\n:::\n\n\n## 문제 5.\n**위 환자의 혈액에서 백혈병 세포가 관측되지 않은 확률은 얼마인가요?**\n\n::: {#cedfa45d .cell execution_count=6}\n``` {.python .cell-code}\np_hat = odds / (odds + 1)\np_hat # 0.03677088280074742)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nnp.float64(0.03677088280074742)\n```\n:::\n:::\n\n\n## 문제 6. \n**TEMP 변수의 계수는 얼마이며, 해당 계수를 사용해서 TEMP 변수가 백혈병 치료에 대한 영향을 설명하시오.**\n\n::: {#924e6f0e .cell execution_count=7}\n``` {.python .cell-code}\nnp.exp(-100.1734)*100 \n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nnp.float64(3.1278444454718354e-42)\n```\n:::\n:::\n\n\n> 계수: -100.1734\n> temp가 1 증가할때 REMISS에 대한 오즈가 3.1278444454718354e-42[%] 로 감소한다.\n> 즉 백혈병 세포가 관측될 확률이 증가한다.\n\n\n## 문제 7. \n**CELL 변수의 99% 오즈비에 대한 신뢰구간을 구하시오.**\n\n::: {#3af96dce .cell execution_count=8}\n``` {.python .cell-code}\nz = norm.ppf(0.995,0,1)\nr_ci = np.exp(30.8301 + z * 52.135)\nl_ci = np.exp(30.8301 - z * 52.135)\nl_ci, r_ci\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n(np.float64(1.1683218982002717e-45), np.float64(5.141881884993857e+71))\n```\n:::\n:::\n\n\n## 문제 8. \n**주어진 데이터에 대하여 로지스틱 회귀 모델의 예측 확률을 구한 후, 50% 이상인 경우 1로 처리하여, 혼동 행렬를 구하시오.**\n\n::: {#c6f09b11 .cell execution_count=9}\n``` {.python .cell-code}\ndf_x=df.drop([\"REMISS\"], axis=1)\ndf_y=df[\"REMISS\"]\n\ny_pred = model.predict(df_x).round().astype(int)\n\nfrom sklearn.metrics import confusion_matrix\nconf_mat=confusion_matrix(y_true=np.array(df_y), \n                          y_pred=np.array(y_pred),\n                          labels=[1, 0])\nconf_mat\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\narray([[ 5,  4],\n       [ 3, 15]])\n```\n:::\n:::\n\n\n## 문제 9. \n**해당 모델의 Accuracy는 얼마인가요?**\n\n::: {#88cffbd7 .cell execution_count=10}\n``` {.python .cell-code}\n(conf_mat[0][0]+conf_mat[1][1])/conf_mat.sum() # 0.7407407407407407\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\nnp.float64(0.7407407407407407)\n```\n:::\n:::\n\n\n## 문제 10. \n**해당 모델의 F1 Score를 구하세요.**\n\n::: {#f6755e21 .cell execution_count=11}\n``` {.python .cell-code}\nprecision=conf_mat[0][0]/(conf_mat[0][0]+conf_mat[1][0])\nrecall=conf_mat[0][0]/(conf_mat[0][0]+conf_mat[0][1])\n\nf1=2/((1/precision)+(1/recall))\nf1 # 0.5882352941176471\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\nnp.float64(0.5882352941176471)\n```\n:::\n:::\n\n\n<div id=\"disqus_thread\"></div>\n<script>\nvar disqus_config = function () {\n    this.page.url = window.location.href;  // 현재 페이지 URL\n    this.page.identifier = window.location.pathname; // 페이지 고유 식별자\n};\n\n(function() { // DON'T EDIT BELOW THIS LINE\n    var d = document, s = d.createElement('script');\n    s.src = 'https://sanghoohoo.disqus.com/embed.js';\n    s.setAttribute('data-timestamp', +new Date());\n    (d.head || d.body).appendChild(s);\n})();\n</script>\n<noscript>Please enable JavaScript to view the <a href=\"https://disqus.com/?ref_noscript\">comments powered by Disqus.</a></noscript>\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}