project:
  type: website
  output-dir: docs

website:
  title: "Sanghoo Ahn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: lsbigdata_blog.qmd
        text: LS bigdata
      - href: project_blog.qmd
        text: Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



