---
title: "HW7"
author: 'Sanghoo Ahn'
date: '2024-09-02'
categories: [bigdata]
jupyter: python3
---

## ADP 표본점수

**2022년에 실시된 ADP실기 시험의 통계파트 표준점수는 평균이 30, 표준편차가 5인 정규분포를 따른다고 한다.**
 
- ADP 실기 시험의 통계파트 표준점수의 밀도함수를 그려보세요

```{python}
from scipy.stats import norm
import numpy as np
import matplotlib.pyplot as plt
k = np.linspace(10, 50, 100)
y = norm.pdf(k, loc=30, scale=5)
plt.plot(k, y)

```
  

- ADP 수험생을 임의로 1명을 선택하여 통계 점수를 조회했을때 45점 보다 높은 점수를 받았을 확률을 구하세요.

```{python}
p = 1-norm.cdf(45, loc=30, scale=5)
print(round(p, 6))
```
  

- 슬통이는 상위 10%에 해당하는 점수를 얻었다고 한다면, 슬통이의 점수는 얼마인지 계산해보세요.

```{python}
score = norm.ppf(0.9, loc=30, scale=5)
print(round(score, 3))
```

- 슬기로운 통계생활의 해당 회차 수강생은 16명이었다고 한다. 16명의 통계 파트 점수를 평균내었을 때, 이 평균값이 따르는 분포의 확률밀도 함수를 1번의 그래프와 겹쳐 그려보세요.

```{python}
k = np.linspace(10, 50, 100)
y = norm.pdf(k, loc=30, scale=5)
plt.plot(k, y)

X_bar = norm.pdf(k, loc=30, scale=5/np.sqrt(16))
plt.plot(k, X_bar)
```

-슬기로운 통계생활 ADP 반 수강생들의 통계점수를 평균내었다고 할 때, 이 값이 38점보다 높게 나올 확률을 구하세요.

```{python}
p = 1-norm.cdf(38, loc=30, scale=5/np.sqrt(16))
print(p)
```


## Covid 19 발병률

**Covid‑19의 발병률은 1%라고 한다. 다음은 이번 코로나 사태로 인하여 코로나 의심 환자들 1,085명을 대상으로 슬통 회사의 “다잡아” 키트를 사용하여 양성 반응을 체크한 결과이다.**

```{python}
import pandas as pd
pd.DataFrame({
    "키트\실제": ["양성", "음성"],
    "양성": [370, 15],
    "음성": [10, 690]
})
```

- 다잡아 키트가 코로나 바이러스에 걸린 사람을 양성으로 잡아낼 확률을 계산하세요.

```{python}
# P(키트 양성|실제 양성)
p = 370 / (370 + 15)
print(round(p, 3))
```

- 슬통 회사에서 다잡아 키트를 사용해 양성으로 나온 사람이 실제로는 코로나 바이러스에 걸려있을 확률을 97%라며, 키트의 우수성을 주장했다. 이 주장이 옳지 않은 이유를 서술하세요.

```
표본집단의 확률인 0.961038961038961과 차이가 큼

```

- Covid‑19 발병률을 사용하여, 키트의 결과값이 양성으로 나온 사람이 실제로 코로나 바이러스에 걸려있을 확률을 구하세요.

$$
\begin{aligned}
P(\text{실제 양성} \mid \text{키트 양성}) &= \frac{P(\text{키트 양성} \cap \text{실제 양성})}{P(\text{키트 양성})} \\
&= \frac{P(\text{실제 양성}) \cdot P(\text{키트 양성} \mid \text{실제 양성})}
{P(\text{실제 양성}) \cdot P(\text{키트 양성} \mid \text{실제 양성}) + P(\text{실제 음성}) \cdot P(\text{키트 양성} \mid \text{실제 음성})}
\end{aligned}
$$

```{python}
p = 0.01*(370/385) / (0.01*(370/385)+0.99*(10/700))
print(round(p, 3))
```


## 카이제곱분포와 표본분산

- 자유도가 4인 카이제곱분포의 확률밀도함수를 그려보세요.

```{python}
from scipy.stats import chi2
k = np.linspace(0, 20, 100)
y = chi2.pdf(k, df=4)
plt.plot(k, y)

```

- 다음의 확률을 구해보세요. 𝑃 (3 ≤ 𝑋 ≤ 5)

```{python}
p = chi2.cdf(5, df=4) - chi2.cdf(3, df=4)
print(round(p, 3))
```

- 자유도가 4인 카이제곱분포에서 크기가 1000인 표본을 뽑은 후, 히스토그램을 그려보세요.

```{python}
import seaborn as sns
np.random.seed(20240902)
x=chi2.rvs(size=1000, df=4)
sns.histplot(x)

```

- 자유도가 4인 카이제곱분포를 따르는 확률변수에서 나올 수 있는 값 중 상위 5%에 해당하는 값은 얼마인지 계산해보세요.

```{python}
x = chi2.ppf(0.95, df=4)
print(round(x, 3))
```

- 3번에서 뽑힌 표본값들 중 상위 5%에 위치한 표본의 값은 얼마인가요?

```{python}
x = np.percentile(x, 95)
print(round(x, 3))

```

- 평균이 3, 표준편차가 2인 정규분포를 따르는 확률변수에서 크기가 20인 표본, x_1, ..., x_20,을 뽑은 후 표본분산을 계산한 것을 s^2_1이라 생각해보죠. 다음을 수행해보세요!

```{python}
# 같은 방법으로 500개의 s^2 들, s^2_1,s^2_2,...,s^2_500 발생시킵니다.
var=[]
for i in range(500):
    x=norm.rvs(size=20, loc=3, scale=2)
    var.append(np.var(x, ddof=1))
```
```{python}
# 발생한 500개의 s^2 들 각각에 4.75를 곱하고, 그것들의 히스토그램을 그려보세요. (히스토그램을 그릴 때 probability = TRUE 옵션을 사용해서 그릴 것)
a=np.array(var)*4.75
sns.histplot(a, stat='density')
# 위에서 그린 히스토그램에 자유도가 19인 카이제곱분포 확률밀도함수를 겹쳐그려보세요.
k = np.linspace(a.min(), a.max(), 100)
y = chi2.pdf(k, df=19)
plt.plot(k, y, color='red')
```



<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
    this.page.url = window.location.href;  // 현재 페이지 URL
    this.page.identifier = window.location.pathname; // 페이지 고유 식별자
};

(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://sanghoohoo.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>